#!/bin/sh
# ------------------------------------------------------------------------------
# build-kernel - Builds the ev3dev kernel
#
# ------------------------------------------------------------------------------

echo
echo -------------------------------------------------------------------------------
echo BUILDING KERNEL
echo -------------------------------------------------------------------------------
echo
sleep 1

project=`pwd`

. ./build_ev3dev_setup

PATH=${AM1808_COMPILER}:$PATH

cd ${AM1808_KERNEL}

if [ "$1" = "distclean" ]
then
  make distclean ARCH=arm CROSS_COMPILE=${AM1808_ABI}
  cp ${project}/ev3dev.config ${AM1808_KERNEL}/.config
fi

if [ "$1" = "modules" ]
then
  make modules ARCH=arm CROSS_COMPILE=${AM1808_ABI}
  exit
fi

if [ "$1" = "modules_install" ]
then
  make modules_install ARCH=arm CROSS_COMPILE=${AM1808_ABI} INSTALL_MOD_PATH=${project}/release
  rm ${project}/release/lib/modules/3.3.0/build
  rm ${project}/release/lib/modules/3.3.0/source

  # Or is it better to just copy the modules and run depmod on the target?
# mkdir -p ${project}/modules/lib/modules/3.3.0
# cp --parents `find . -name "*.ko"` ${project}/modules/lib/modules/3.3.0
  exit
fi

cp ${project}/ev3dev.config ${AM1808_KERNEL}/.config

echo "CROSS COMPILING KERNEL"

make ARCH=arm CROSS_COMPILE=${AM1808_ABI}

echo "BUILDING BOOTABLE IMAGE"

make -j4 uImage ARCH=arm CROSS_COMPILE=${AM1808_ABI}

echo "COPYING BOOTABLE IMAGE TO LOCAL DIRECTORY"

cp ${AM1808_KERNEL}/arch/arm/boot/uImage ${project}/uImage


