#!/bin/sh

. ./setup-env

if [ ! -f $AM1808_INSTALL ]
then
        mkdir -p $AM1808_INSTALL || exit $?
fi

mkimage -A arm -O linux -T script -C none -a 0 -e 0 -n "ev3dev" -d boot.cmd $AM1808_INSTALL/boot.scr

