#!/bin/sh
# ------------------------------------------------------------------------------
# build-modules - Builds the ev3dev modules
#
# ------------------------------------------------------------------------------

echo
echo -------------------------------------------------------------------------------
echo BUILDING MODULES
echo -------------------------------------------------------------------------------
echo
sleep 1

project=`pwd`

. ./build_ev3dev_setup

PATH=${AM1808_COMPILER}:$PATH

echo ${PATH}

MODDESTDIR=${project}/release/lib/modules/3.3.0/kernel/drivers/ev3dev

# if [ ! -e modules ]; then
#   mkdir -p ./modules
# fi

# for module in "ev3dev" "ui" "pwm"
# for module in "ev3dev" "ui"
# for module in "ev3dev" "pwm" 
  for module in "pwm" 
do 
    cd ${project}/../ev3dev-modules/lms2012/d_${module}/Linuxmod_AM1808
    echo "Now we're in $(pwd)"
    make -C ${AM1808_KERNEL} M=`pwd` MOD=${module} ARCH=arm CROSS_COMPILE=${AM1808_ABI} modules

    if [ "${module}" = "ev3dev" ]; then
        install -p -D -m 644 ev3dev.ko            ${MODDESTDIR}/${module}.ko
    else
        install -p -D -m 644 ev3dev_${module}.ko  ${MODDESTDIR}/ev3dev_${module}.ko
    fi
    
done

#    make -C ${AM1808_KERNEL} MOD=${module} M=`pwd` ARCH=arm CROSS_COMPILE=${AM1808_ABI} modules
# cp $1.ko $AM1808_MODULES/$1.ko

