#!/bin/sh -e
echo $PATH
if [ ! -z $DEBIAN_MIRROR ]; then
	DEBIAN_MIRROR="-m $DEBIAN_MIRROR"
fi

polystrap -d ev3dev-rootfs $DEBIAN_MIRROR ev3dev

# guestfish does not know how to set label for vfat!

guestfish -N bootroot:vfat:ext3:512M:48M:mbr \
set-label /dev/sda2 EV3_FILESYS : \
mount /dev/sda2 / : \
tar-in ev3dev-rootfs.tar.gz / compress:gzip : \
mkdir-p /media/mmc_p1 : \
mount /dev/sda1 /media/mmc_p1 : \
mv /uImage /media/mmc_p1/ : \
mv /uInitrd /media/mmc_p1/ : \
mv /boot.scr /media/mmc_p1/ : \
mv /ev3dev.rc.local /media/mmc_p1/

mv test1.img ev3dev.img
zip -9 ev3dev.img.zip ev3dev.img
cat ev3dev.img | xz -9 > ev3dev.img.xz

