#!/bin/sh
# ------------------------------------------------------------------------------
# menuconfig - Runs make menuconfig
# ------------------------------------------------------------------------------

project=`pwd`
cd "../ev3dev-kernel" || exit $?
make ARCH=arm menuconfig


