#!/bin/sh
# ------------------------------------------------------------------------------
# sdcard-img-populate - mounts the image created by sdcard-img-create and
#                       populates it using ../ev3dev-rootfs files, then adds
#                       modules, drivers, firmware etc separately
#
# ------------------------------------------------------------------------------

die() { echo -n >&2 "\n$0: $@\n"; exit 1; }

# ------------------------------------------------------------------------------
# Make sure we're running as root, and that we have found the right sdcard!

[ "$(whoami)" != "root" ] && die "Sorry, you are not root!"

# ------------------------------------------------------------------------------
# Make sure we want to overwrite the file if it already exists!

echo    "-------------------------------------------------------------------------------"
echo    "WARNING - If you type \"Yes\" to the prompt, this script"
echo    "          will OVERWRITE the ev3dev.img file!"
echo    "-------------------------------------------------------------------------------"

echo -n "   Type \"Yes\" to continue ... "
read YesNo

[ ! "${YesNo}" = "Yes" ] && die " .. aborting, you typed \"${YesNo}\""

# ------------------------------------------------------------------------------
# Create the mount points for the ev3dev card partitions if they do not already
# exist...

echo    "-------------------------------------------------------------------------------"
echo -n "   Type \"Yes\" to populate the ev3dev.img file ... "
read YesNo

[ ! "${YesNo}" = "Yes" ] && die " .. aborting, you typed \"${YesNo}\""

echo
echo -n "   Checking for ev3dev-fat32 mountpoint, will create if needed ... "
[ -e ev3dev-fat32 ] && [ ! -d ev3dev-fat32 ] && die "ev3dev-fat32 exists, but it's a file!"
[ ! -e ev3dev-fat32 ] && mkdir ev3dev-fat32 
echo    "done."

echo -n "   Checking for ev3dev-ext3 mountpoint, will create if needed ... "
[ -e ev3dev-ext3 ] && [ ! -d ev3dev-ext3 ] && die "ev3dev-ext3 exists, but it's a file!"
[ ! -e ev3dev-ext3 ] && mkdir ev3dev-ext3 
echo    "done."

echo    "-------------------------------------------------------------------------------"
echo    "   Unmounting ev3dev.img partitions ... "

eval umount "/dev/mapper/loop?-ev3dev-1" > /dev/null 2>&1
eval umount "/dev/mapper/loop?-ev3dev-2" > /dev/null 2>&1 

echo    "-------------------------------------------------------------------------------"
echo    "   Unmapping partitions from ev3dev.img ... "
echo

kpartx -vlsd -p"-ev3dev-" ./ev3dev.img

echo    "-------------------------------------------------------------------------------"
echo    "   Mapping partitions from ev3dev.img ... "
echo

kpartx -vlsa -p"-ev3dev-" ./ev3dev.img

echo    "-------------------------------------------------------------------------------"
echo    "   Mounting ev3dev.img partitions ... "

eval mount "/dev/mapper/loop?-ev3dev-1" "./ev3dev-fat32"
eval mount "/dev/mapper/loop?-ev3dev-2" "./ev3dev-ext3"

echo    "-------------------------------------------------------------------------------"
echo -n "   Copying uImage and ev3dev.rc.local to the fat32 partition ... "

cp -dR rootfs-updates/boot_part/* ev3dev-fat32

echo    "done."

echo    "-------------------------------------------------------------------------------"
echo -n "   Copying the bare rootfs to the ev3dev partition ... "

cp -dR ../ev3dev-rootfs/ev3-rootfs/* ev3dev-ext3

echo    "done."

echo    "-------------------------------------------------------------------------------"
echo -n "   Copying the kernel modules to the ev3dev partition ... "

cp -dR rootfs-updates/linux_part/lib/* ev3dev-ext3/lib

echo    "done."

echo    "-------------------------------------------------------------------------------"
echo -n "   Copying the modified /etc files to the ev3dev partition ... "

cp -dR rootfs-updates/linux_part/etc/* ev3dev-ext3/etc

echo    "done."

echo    "-------------------------------------------------------------------------------"
echo -n "   Creating mount point directories in /media ... "

mkdir ev3dev-ext3/media/mmc_p1

echo    "done."

echo    "-------------------------------------------------------------------------------"
echo -n "   Filling unused sectors on FAT32 partition with zeros ... "

dd if=/dev/zero of=ev3dev-fat32/zero.fill > /dev/null 2>&1
sleep 3
rm ev3dev-fat32/zero.fill

echo    "done."

echo    "-------------------------------------------------------------------------------"
echo -n "   Filling unused sectors on ext3 partition with zeros ... "

dd if=/dev/zero of=ev3dev-ext3/zero.fill > /dev/null 2>&1
sleep 3
rm ev3dev-ext3/zero.fill

echo    "done."

echo    "-------------------------------------------------------------------------------"
echo    "   Unmounting ev3dev.img partitions ... "

eval umount "/dev/mapper/loop?-ev3dev-1" > /dev/null 2>&1
eval umount "/dev/mapper/loop?-ev3dev-2" > /dev/null 2>&1 

echo    "-------------------------------------------------------------------------------"
echo    "   Unmapping partitions from ev3dev.img ... "
echo

kpartx -vlsd -p"-ev3dev-" ./ev3dev.img

echo "-------------------------------------------------------------------------------"
exit
