#!/bin/sh
# ------------------------------------------------------------------------------
# sdcard-img-mount - mounts the image created by sdcard-img-create
#
# ------------------------------------------------------------------------------

die() { echo -n >&2 "\n$0: $@\n"; exit 1; }

# ------------------------------------------------------------------------------
# Make sure we're running as root, and that we have found the right sdcard!

[ "$(whoami)" != "root" ] && die "Sorry, you are not root!"

# ------------------------------------------------------------------------------
# Unmount the ev3dev card partitions - failsafe in case they are already mounted
# exist...

echo    "-------------------------------------------------------------------------------"
echo    "   Unmounting ev3dev.img partitions ... "

eval umount "/dev/mapper/loop?-ev3dev-1" > /dev/null 2>&1
eval umount "/dev/mapper/loop?-ev3dev-2" > /dev/null 2>&1 

echo    "-------------------------------------------------------------------------------"
echo    "   Unmapping partitions from ev3dev.img ... "
echo

kpartx -vlsd -p"-ev3dev-" ./ev3dev.img

# ------------------------------------------------------------------------------
# Create the mount points for the ev3dev card partitions if they do not already
# exist...

echo    "-------------------------------------------------------------------------------"
echo -n "   Type \"Yes\" to continue to mount the ev3dev.img file ... "
read YesNo

if [ "${YesNo}" = "Yes" ]; then

    echo
    echo -n "   Checking for ev3dev-fat32 mountpoint, will create if needed ... "
    [ -e ev3dev-fat32 ] && [ ! -d ev3dev-fat32 ] && die "ev3dev-fat32 exists, but it's a file!"
    [ ! -e ev3dev-fat32 ] && mkdir ev3dev-fat32 
    echo    "done."

    echo -n "   Checking for ev3dev-ext3 mountpoint, will create if needed ... "
    [ -e ev3dev-ext3 ] && [ ! -d ev3dev-ext3 ] && die "ev3dev-ext3 exists, but it's a file!"
    [ ! -e ev3dev-ext3 ] && mkdir ev3dev-ext3 
    echo    "done."

    echo    "-------------------------------------------------------------------------------"
    echo    "   Mapping partitions from ev3dev.img ... "
    echo

    kpartx -vlsa -p"-ev3dev-" ./ev3dev.img

    echo    "-------------------------------------------------------------------------------"
    echo    "   Mounting ev3dev.img partitions ... "

    eval mount "/dev/mapper/loop?-ev3dev-1" "./ev3dev-fat32"
    eval mount "/dev/mapper/loop?-ev3dev-2" "./ev3dev-ext3"
fi

echo "-------------------------------------------------------------------------------"
exit
