#!/bin/sh
# ------------------------------------------------------------------------------
# setup-env - Sets up a bunch of standard environment variables in
#             preparation for a cross-compile of the kernel, modules,
#             or other code that needs to run on the ev3dev distro.
#
# You can override the variables here by creating a file either in the
# working directory (./local-env) or in your home directory (~/.ev3dev-env).
# If both files are present, the one in the working directory takes
# precedence.
#
# This file is normally source'd from within the actual build script using:
#
# . ./setup-env
#
# Note that the variables prefixed with LEGO_ are only there to make it 
# easier to switch to building the stock LEGO image, which I did at the 
# beginning to verify the compiler toolchain.
#
# The variables prefixed with EV3DEV_ are the ones we'll use for building
# the ev3dev distribution.
#
# And finally, the AM1808_ prefixed variables are the ones the build
# scripts use to get to the source and executables. These are the ones
# that you should override in your local files.
#
# ------------------------------------------------------------------------------


export AM1808_COMPILER="../bin/arm-2011.03/bin"

export LEGO_AM1808_DISTRO="lego-DaVinci-PSP-SDK-03.20.00.13"
export LEGO_AM1808_LINUX="linux-03.20.00.13"
export LEGO_AM1808_UBOOT="uboot-03.20.00.13"
export LEGO_AM1808_ABI="arm-none-eabi-"

export LEGO_AM1808_KERNEL="/opt/${LEGO_AM1808_DISTRO}/src/kernel/${LEGO_AM1808_LINUX}"

export EV3DEV_AM1808_DISTRO=".."
export EV3DEV_AM1808_LINUX="ev3dev-kernel"
export EV3DEV_AM1808_ABI="arm-none-eabi-"

export AM1808_DISTRO="${EV3DEV_AM1808_DISTRO}"
export AM1808_LINUX="${EV3DEV_AM1808_LINUX}"
export AM1808_ABI="${EV3DEV_AM1808_ABI}"
export AM1808_OBJ="${AM1808_DISTRO}/obj"
export AM1808_KERNEL="${AM1808_DISTRO}/${AM1808_LINUX}"
export AM1808_INSTALL="${AM1808_DISTRO}/dist"
export EV3DEV_MERGE_CMD="vimdiff \$file1 \$file2"

#export AM1808_MODULES=~/projects/lms2012/lms2012/Linux_AM1808/sys/mod

#export X86_KERNEL=/lib/modules/$(uname -r)/build
#export X86_MODULES=~/projects/lms2012/lms2012/Linux_X86/sys/mod

if [ -f ~/.ev3dev-env ]
then
	. ~/.ev3dev-env
fi

if [ -f local-env ]
then
	. ./local-env
fi

